UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glucose(Urine)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Urobilinogen Phenlpyruvic Acid(Urine)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Fasting blood sugar(Urine/Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Random blood sugar(Urine/Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'OGTT(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Renal function tests(Urine)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Creatinine(Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Urea(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Sodium(Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Potassium(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Chloride(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Direct bilirubin(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Total bilirubin(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'SGPT/ALAT(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'SGOT/ASAT(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Serum Protein(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Albumin(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Alkaline Phodphate(Urine)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Gamma GT(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Amylase(Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Total cholestrol(Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Trigycerides(Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'HDL(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'LDE(Blood)');
UPDATE clinlims.test_result SET significant_digits = 3 WHERE test_id=(select id from clinlims.test where description = 'PSA(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'CSF Proteins(Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'CSF Glucose(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Proteins(Blood)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Glucose(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Acid phosphatase(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Bence jones protein(Urine)');
UPDATE clinlims.test_result SET significant_digits = 3 WHERE test_id=(select id from clinlims.test where description = 'Triiodothyronine(T3)(Blood)');
UPDATE clinlims.test_result SET significant_digits = 3 WHERE test_id=(select id from clinlims.test where description = 'Thyroid-stimulating Hormone(TSH)(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Full blood count(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Manual WBCcounts(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Peripheral blood films(Swab)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Erythrocyte Sedimentation rate(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Hb electrophoresis(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'G6PD screening(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Bleeding time(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Clotting time(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Prothrombin test(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Partial prothrombin time(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Reticulocyte counts(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Haemoglobin(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'CD4/CD8(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'CD4%(Blood)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Viral Load(Blood)');
