INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mg/dL') , 'Glucose(Urine)' , '',  'Glucose' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Glucose' ,1210 , 'Glucose',  true, '477cf060-6deb-4ea9-a9ef-c9af353a7730', (select id from clinlims.localization where english = 'Glucose' and description = 'test name'), (select id from clinlims.localization where english = 'Glucose' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Ketones(Urine)' , '',  'Ketones' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Ketones' ,1220 , 'Ketones',  true, 'f97097fa-4b87-4964-96a7-be9e45fcdd5c', (select id from clinlims.localization where english = 'Ketones' and description = 'test name'), (select id from clinlims.localization where english = 'Ketones' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Blood(Urine)' , '',  'Blood' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Blood' ,1230 , 'Blood',  true, '9840797a-1892-4d59-8f1a-f05f5a361433', (select id from clinlims.localization where english = 'Blood' and description = 'test name'), (select id from clinlims.localization where english = 'Blood' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Bilirubin(Urine)' , '',  'Bilirubin' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Bilirubin' ,1240 , 'Bilirubin',  true, '27b1173e-c7b3-44a0-912f-a5a90a426b90', (select id from clinlims.localization where english = 'Bilirubin' and description = 'test name'), (select id from clinlims.localization where english = 'Bilirubin' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mg/dL') , 'Urobilinogen Phenlpyruvic Acid(Urine)' , '',  'Urobilinogen' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Urobilinogen Phenlpy' ,1250 , 'Urobilinogen Phenlpyruvic Acid',  true, 'acb6803f-2404-45de-b9bc-1a84ccc65907', (select id from clinlims.localization where english = 'Urobilinogen Phenlpyruvic Acid' and description = 'test name'), (select id from clinlims.localization where english = 'Urobilinogen Phenlpyruvic Acid' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'HGC(Urine)' , '',  'HGC' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'HGC' ,1260 , 'HGC',  true, 'bd729afc-84f5-4955-aea6-d52f08ac3493', (select id from clinlims.localization where english = 'HGC' and description = 'test name'), (select id from clinlims.localization where english = 'HGC' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Pus Cells (>5/hpf)(Urine)' , '',  'Pus' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Pus Cells (>5/hpf)' ,1270 , 'Pus Cells (>5/hpf)',  true, 'af934d86-7e46-40bd-a046-15b26e0971df', (select id from clinlims.localization where english = 'Pus Cells (>5/hpf)' and description = 'test name'), (select id from clinlims.localization where english = 'Pus Cells (>5/hpf)' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'S. haematobium(Urine)' , '',  'S.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'S. haematobium' ,1280 , 'S. haematobium',  true, 'cc737df4-49a7-4784-9787-135321a7a47f', (select id from clinlims.localization where english = 'S. haematobium' and description = 'test name'), (select id from clinlims.localization where english = 'S. haematobium' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'T. vaginalis(Swab/Urine)' , '',  'T.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'T. vaginalis' ,1290 , 'T. vaginalis',  true, 'a081781b-8d83-4f2c-bb6a-7c7064c00373', (select id from clinlims.localization where english = 'T. vaginalis' and description = 'test name'), (select id from clinlims.localization where english = 'T. vaginalis' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Yeast Cells(Swab/Urine)' , '',  'Yeast' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Yeast Cells' ,1300 , 'Yeast Cells',  true, '98496580-da58-4158-a845-78305c56c8e0', (select id from clinlims.localization where english = 'Yeast Cells' and description = 'test name'), (select id from clinlims.localization where english = 'Yeast Cells' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Red blood cells(Urine)' , '',  'Red' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Red blood cells' ,1310 , 'Red blood cells',  true, 'd5a12326-dfcb-4c23-aba7-fb686438fd3e', (select id from clinlims.localization where english = 'Red blood cells' and description = 'test name'), (select id from clinlims.localization where english = 'Red blood cells' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Bacteria(Urine)' , '',  'Bacteria' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Bacteria' ,1320 , 'Bacteria',  true, '5029b9d9-8773-4ac8-997e-4e50b3cb46f1', (select id from clinlims.localization where english = 'Bacteria' and description = 'test name'), (select id from clinlims.localization where english = 'Bacteria' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Spermatozoa(Urine)' , '',  'Spermatozoa' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Spermatozoa' ,1330 , 'Spermatozoa',  true, '0b49bf1b-1778-45b8-9485-54544e60e4a1', (select id from clinlims.localization where english = 'Spermatozoa' and description = 'test name'), (select id from clinlims.localization where english = 'Spermatozoa' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Fasting blood sugar(Urine/Blood)' , '',  'Fasting' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Fasting blood sugar' ,1340 , 'Fasting blood sugar',  true, '850ac703-946c-4688-8a1c-6c05bc2ff04e', (select id from clinlims.localization where english = 'Fasting blood sugar' and description = 'test name'), (select id from clinlims.localization where english = 'Fasting blood sugar' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Random blood sugar(Urine/Blood)' , '',  'Random' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Random blood sugar' ,1350 , 'Random blood sugar',  true, 'd6ee6d29-ba33-4026-a329-828e6cf3f993', (select id from clinlims.localization where english = 'Random blood sugar' and description = 'test name'), (select id from clinlims.localization where english = 'Random blood sugar' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mg/dL') , 'OGTT(Blood)' , '',  'OGTT' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'OGTT' ,1360 , 'OGTT',  true, '136ccf6b-60ba-4649-af24-0ce8b239e388', (select id from clinlims.localization where english = 'OGTT' and description = 'test name'), (select id from clinlims.localization where english = 'OGTT' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Renal function tests(Urine)' , '',  'Renal' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Renal function tests' ,1370 , 'Renal function tests',  true, '5071b0f4-5ce8-4d0a-9935-02e631c52392', (select id from clinlims.localization where english = 'Renal function tests' and description = 'test name'), (select id from clinlims.localization where english = 'Renal function tests' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='umol/L') , 'Creatinine(Blood)' , '',  'Creatinine' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Creatinine' ,1380 , 'Creatinine',  true, '99d67895-b91e-4e04-8a27-b6174d10daa6', (select id from clinlims.localization where english = 'Creatinine' and description = 'test name'), (select id from clinlims.localization where english = 'Creatinine' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Urea(Blood)' , '',  'Urea' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Urea' ,1390 , 'Urea',  true, '67a26c89-330d-4be5-91d8-8728c25cc1a2', (select id from clinlims.localization where english = 'Urea' and description = 'test name'), (select id from clinlims.localization where english = 'Urea' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Sodium(Blood)' , '',  'Sodium' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Sodium' ,1400 , 'Sodium',  true, '30f5fc93-fc16-48f3-beb1-72713d664e0c', (select id from clinlims.localization where english = 'Sodium' and description = 'test name'), (select id from clinlims.localization where english = 'Sodium' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Potassium(Blood)' , '',  'Potassium' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Potassium' ,1410 , 'Potassium',  true, '5b3179da-66c3-413d-82df-d1eb56c2536a', (select id from clinlims.localization where english = 'Potassium' and description = 'test name'), (select id from clinlims.localization where english = 'Potassium' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Chloride(Blood)' , '',  'Chloride' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Chloride' ,1420 , 'Chloride',  true, 'f88e0e1b-ebe1-4afe-97ac-7c10b070a05f', (select id from clinlims.localization where english = 'Chloride' and description = 'test name'), (select id from clinlims.localization where english = 'Chloride' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Direct bilirubin(Blood)' , '',  'Direct' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Direct bilirubin' ,1430 , 'Direct bilirubin',  true, 'b4f4dd29-f67c-4ec8-9c53-b5c6cf6099b0', (select id from clinlims.localization where english = 'Direct bilirubin' and description = 'test name'), (select id from clinlims.localization where english = 'Direct bilirubin' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Total bilirubin(Blood)' , '',  'Total' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Total bilirubin' ,1440 , 'Total bilirubin',  true, 'bd82fbcb-a0dd-44c8-826c-e5339087cdbd', (select id from clinlims.localization where english = 'Total bilirubin' and description = 'test name'), (select id from clinlims.localization where english = 'Total bilirubin' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='U/L') , 'SGPT/ALAT(Blood)' , '',  'SGPT/ALAT' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'SGPT/ALAT' ,1450 , 'SGPT/ALAT',  true, '8092c2f7-4927-4e94-a3ef-c45c90aedf06', (select id from clinlims.localization where english = 'SGPT/ALAT' and description = 'test name'), (select id from clinlims.localization where english = 'SGPT/ALAT' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='U/L') , 'SGOT/ASAT(Blood)' , '',  'SGOT/ASAT' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'SGOT/ASAT' ,1460 , 'SGOT/ASAT',  true, 'c368a373-1647-4287-b633-00893dfc4b71', (select id from clinlims.localization where english = 'SGOT/ASAT' and description = 'test name'), (select id from clinlims.localization where english = 'SGOT/ASAT' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/L') , 'Serum Protein(Blood)' , '',  'Serum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Serum Protein' ,1470 , 'Serum Protein',  true, '1c1b4698-6891-4ebb-b9e7-31117bc416a2', (select id from clinlims.localization where english = 'Serum Protein' and description = 'test name'), (select id from clinlims.localization where english = 'Serum Protein' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/L') , 'Albumin(Blood)' , '',  'Albumin' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Albumin' ,1480 , 'Albumin',  true, 'd93f88dc-e34d-42bc-86b8-fe6a68ef7782', (select id from clinlims.localization where english = 'Albumin' and description = 'test name'), (select id from clinlims.localization where english = 'Albumin' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Alkaline Phodphate(Urine)' , '',  'Alkaline' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Alkaline Phodphate' ,1490 , 'Alkaline Phodphate',  true, '9de5acc1-09d1-4908-8a48-b0616dbadd99', (select id from clinlims.localization where english = 'Alkaline Phodphate' and description = 'test name'), (select id from clinlims.localization where english = 'Alkaline Phodphate' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='U/L') , 'Gamma GT(Blood)' , '',  'Gamma' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Gamma GT' ,1500 , 'Gamma GT',  true, 'bad64192-b5b2-450d-8bd2-b6b6c7143122', (select id from clinlims.localization where english = 'Gamma GT' and description = 'test name'), (select id from clinlims.localization where english = 'Gamma GT' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='U/L') , 'Amylase(Blood)' , '',  'Amylase' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Amylase' ,1510 , 'Amylase',  true, 'e11e3fcd-d459-48e9-b6ef-9c56f13091cf', (select id from clinlims.localization where english = 'Amylase' and description = 'test name'), (select id from clinlims.localization where english = 'Amylase' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Total cholestrol(Blood)' , '',  'Total' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Total cholestrol' ,1520 , 'Total cholestrol',  true, '6765796d-9955-453e-bb03-fe910b5893bc', (select id from clinlims.localization where english = 'Total cholestrol' and description = 'test name'), (select id from clinlims.localization where english = 'Total cholestrol' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Trigycerides(Blood)' , '',  'Trigycerides' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Trigycerides' ,1530 , 'Trigycerides',  true, '8ddff0e6-e505-47b1-8cc3-c4ce6f2b2b82', (select id from clinlims.localization where english = 'Trigycerides' and description = 'test name'), (select id from clinlims.localization where english = 'Trigycerides' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'HDL(Blood)' , '',  'HDL' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'HDL' ,1540 , 'HDL',  true, '445fde65-bd84-43b7-8dc8-4d7732614f75', (select id from clinlims.localization where english = 'HDL' and description = 'test name'), (select id from clinlims.localization where english = 'HDL' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'LDE(Blood)' , '',  'LDE' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'LDE' ,1550 , 'LDE',  true, 'b4e1cc38-e4a2-4dfa-9019-1a0bb57b6512', (select id from clinlims.localization where english = 'LDE' and description = 'test name'), (select id from clinlims.localization where english = 'LDE' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/L') , 'PSA(Blood)' , '',  'PSA' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'PSA' ,1560 , 'PSA',  true, 'e1a0b9fc-f548-4125-92b7-319e959958ae', (select id from clinlims.localization where english = 'PSA' and description = 'test name'), (select id from clinlims.localization where english = 'PSA' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'CSF Proteins(Blood)' , '',  'CSF' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'CSF Proteins' ,1570 , 'CSF Proteins',  true, '83bd6524-5d59-4e6e-80d3-8b01ddd77f91', (select id from clinlims.localization where english = 'CSF Proteins' and description = 'test name'), (select id from clinlims.localization where english = 'CSF Proteins' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'CSF Glucose(Blood)' , '',  'CSF' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'CSF Glucose' ,1580 , 'CSF Glucose',  true, 'd578deec-82ca-42fd-b30e-6df66c57724c', (select id from clinlims.localization where english = 'CSF Glucose' and description = 'test name'), (select id from clinlims.localization where english = 'CSF Glucose' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/L') , 'Proteins(Blood)' , '',  'Proteins' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Proteins' ,1590 , 'Proteins',  true, 'ba76f65f-f42e-4032-b4cf-f9808b7b91be', (select id from clinlims.localization where english = 'Proteins' and description = 'test name'), (select id from clinlims.localization where english = 'Proteins' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mmol/L') , 'Glucose(Blood)' , '',  'Glucose' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Glucose' ,1600 , 'Glucose',  true, 'c888cd7a-c615-4771-8b27-baa18f657def', (select id from clinlims.localization where english = 'Glucose' and description = 'test name'), (select id from clinlims.localization where english = 'Glucose' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='U/L') , 'Acid phosphatase(Blood)' , '',  'Acid' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Acid phosphatase' ,1610 , 'Acid phosphatase',  true, 'df661892-b2e0-4e15-8647-ebabe4f8d41f', (select id from clinlims.localization where english = 'Acid phosphatase' and description = 'test name'), (select id from clinlims.localization where english = 'Acid phosphatase' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Bence jones protein(Urine)' , '',  'Bence' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Bence jones protein' ,1620 , 'Bence jones protein',  true, '68a41d03-0236-46a3-ad58-b168c143dd53', (select id from clinlims.localization where english = 'Bence jones protein' and description = 'test name'), (select id from clinlims.localization where english = 'Bence jones protein' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mIU/L') , 'Triiodothyronine(T3)(Blood)' , '',  'Triiodothyronine(T3)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Triiodothyronine(T3)' ,1630 , 'Triiodothyronine(T3)',  true, '873ac9c9-5b73-4c7e-8133-007fa93b17ab', (select id from clinlims.localization where english = 'Triiodothyronine(T3)' and description = 'test name'), (select id from clinlims.localization where english = 'Triiodothyronine(T3)' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mIU/L') , 'Thyroid-stimulating Hormone(TSH)(Blood)' , '',  'Thyroid-stimulating' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'URINALYSIS' ) ,'Thyroid-stimulating ' ,1640 , 'Thyroid-stimulating Hormone(TSH)',  true, '5024a7b1-c35f-4a5b-bb02-382b990883e2', (select id from clinlims.localization where english = 'Thyroid-stimulating Hormone(TSH)' and description = 'test name'), (select id from clinlims.localization where english = 'Thyroid-stimulating Hormone(TSH)' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Falciparum(Smear)' , '',  'Falciparum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Falciparum' ,1650 , 'Falciparum',  true, '5e4afd60-13ce-4e64-bbb2-7f332c2e83b5', (select id from clinlims.localization where english = 'Falciparum' and description = 'test name'), (select id from clinlims.localization where english = 'Falciparum' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Ovale(Smear)' , '',  'Ovale' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Ovale' ,1660 , 'Ovale',  true, '979933dc-ecfa-453b-aa12-383b1e6e273b', (select id from clinlims.localization where english = 'Ovale' and description = 'test name'), (select id from clinlims.localization where english = 'Ovale' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Malariae(Smear)' , '',  'Malariae' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Malariae' ,1670 , 'Malariae',  true, '5351747a-551a-4325-8f61-9209d0726998', (select id from clinlims.localization where english = 'Malariae' and description = 'test name'), (select id from clinlims.localization where english = 'Malariae' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Vivax(Smear)' , '',  'Vivax' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Vivax' ,1680 , 'Vivax',  true, 'ac69d71d-99a1-4213-87c4-5797395aafed', (select id from clinlims.localization where english = 'Vivax' and description = 'test name'), (select id from clinlims.localization where english = 'Vivax' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Borrelia(Smear)' , '',  'Borrelia' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Borrelia' ,1690 , 'Borrelia',  true, '2fcfbb52-47a1-4f83-b756-d75a18d3092a', (select id from clinlims.localization where english = 'Borrelia' and description = 'test name'), (select id from clinlims.localization where english = 'Borrelia' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Trypanosomes(Smear)' , '',  'Trypanosomes' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Trypanosomes' ,1700 , 'Trypanosomes',  true, 'c728a59d-ae0d-4a88-8288-a5212c71059a', (select id from clinlims.localization where english = 'Trypanosomes' and description = 'test name'), (select id from clinlims.localization where english = 'Trypanosomes' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'T. vaginalis(Genital Smears)' , '',  'T.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'T. vaginalis' ,1710 , 'T. vaginalis',  true, '2b677eec-5f9a-446b-ab00-e9f50f30d09b', (select id from clinlims.localization where english = 'T. vaginalis' and description = 'test name'), (select id from clinlims.localization where english = 'T. vaginalis' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'S. haematobium(Genital Smears)' , '',  'S.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'S. haematobium' ,1720 , 'S. haematobium',  true, '3284ad86-fb42-46ff-8147-aca2368a1f0f', (select id from clinlims.localization where english = 'S. haematobium' and description = 'test name'), (select id from clinlims.localization where english = 'S. haematobium' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Yeast cells(Genital Smears)' , '',  'Yeast' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Yeast cells' ,1730 , 'Yeast cells',  true, 'd9202f19-432b-4146-9f3d-8152ababe4d6', (select id from clinlims.localization where english = 'Yeast cells' and description = 'test name'), (select id from clinlims.localization where english = 'Yeast cells' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'L. donovani(Bone Marrow)' , '',  'L.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'L. donovani' ,1740 , 'L. donovani',  true, '1ec2ac73-04d0-460f-9cd9-ccbd709cc156', (select id from clinlims.localization where english = 'L. donovani' and description = 'test name'), (select id from clinlims.localization where english = 'L. donovani' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Taenia spp.(Stool)' , '',  'Taenia' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Taenia spp.' ,1750 , 'Taenia spp.',  true, '17f1d474-5b77-458e-90a5-5805c85d234a', (select id from clinlims.localization where english = 'Taenia spp.' and description = 'test name'), (select id from clinlims.localization where english = 'Taenia spp.' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'H. nana(Stool)' , '',  'H.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'H. nana' ,1760 , 'H. nana',  true, 'a6027243-3bdf-4173-8438-f88597cafc58', (select id from clinlims.localization where english = 'H. nana' and description = 'test name'), (select id from clinlims.localization where english = 'H. nana' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'H. diminuta(Stool)' , '',  'H.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'H. diminuta' ,1770 , 'H. diminuta',  true, '677c00af-4c91-4ef0-8a47-5dddbf02dfad', (select id from clinlims.localization where english = 'H. diminuta' and description = 'test name'), (select id from clinlims.localization where english = 'H. diminuta' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Hookworm(Stool)' , '',  'Hookworm' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Hookworm' ,1780 , 'Hookworm',  true, 'f7e252dc-acd2-41f2-8706-3ff4ecfd8199', (select id from clinlims.localization where english = 'Hookworm' and description = 'test name'), (select id from clinlims.localization where english = 'Hookworm' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Roundworms(Stool)' , '',  'Roundworms' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Roundworms' ,1790 , 'Roundworms',  true, '6d49e06e-4156-47f5-b363-5a5afd72d407', (select id from clinlims.localization where english = 'Roundworms' and description = 'test name'), (select id from clinlims.localization where english = 'Roundworms' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'S. mansoni(Stool)' , '',  'S.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'S. mansoni' ,1800 , 'S. mansoni',  true, 'a829ab8f-60d7-4986-86cb-9ada62b21d70', (select id from clinlims.localization where english = 'S. mansoni' and description = 'test name'), (select id from clinlims.localization where english = 'S. mansoni' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Trichuris trichiura(Stool)' , '',  'Trichuris' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Trichuris trichiura' ,1810 , 'Trichuris trichiura',  true, 'dfde5d83-b04b-463d-a0e2-caa784d649bc', (select id from clinlims.localization where english = 'Trichuris trichiura' and description = 'test name'), (select id from clinlims.localization where english = 'Trichuris trichiura' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Strongyloides stercoralis(Stool)' , '',  'Strongyloides' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Strongyloides sterco' ,1820 , 'Strongyloides stercoralis',  true, '5f7c6e35-f346-4f0c-a60f-29ac5845bc14', (select id from clinlims.localization where english = 'Strongyloides stercoralis' and description = 'test name'), (select id from clinlims.localization where english = 'Strongyloides stercoralis' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Isospora belli(Stool)' , '',  'Isospora' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Isospora belli' ,1830 , 'Isospora belli',  true, '78bc3d53-21a1-4ec2-85cd-a4bb05b1e389', (select id from clinlims.localization where english = 'Isospora belli' and description = 'test name'), (select id from clinlims.localization where english = 'Isospora belli' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'E hystolytica(Stool)' , '',  'E' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'E hystolytica' ,1840 , 'E hystolytica',  true, 'd69fcbec-2fe2-4cdb-a605-e2c403d2e4e7', (select id from clinlims.localization where english = 'E hystolytica' and description = 'test name'), (select id from clinlims.localization where english = 'E hystolytica' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Giardia lamblia(Stool)' , '',  'Giardia' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Giardia lamblia' ,1850 , 'Giardia lamblia',  true, '607e4c22-f7b6-422d-9008-f1accf348e1b', (select id from clinlims.localization where english = 'Giardia lamblia' and description = 'test name'), (select id from clinlims.localization where english = 'Giardia lamblia' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Cryptosporidium(Stool)' , '',  'Cryptosporidium' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Cryptosporidium' ,1860 , 'Cryptosporidium',  true, '60c9c3fa-73fa-4334-8dc1-c05d6c4aa167', (select id from clinlims.localization where english = 'Cryptosporidium' and description = 'test name'), (select id from clinlims.localization where english = 'Cryptosporidium' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Cyclospora(Stool)' , '',  'Cyclospora' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Cyclospora' ,1870 , 'Cyclospora',  true, '4c1fb76a-0ee6-440e-8ea0-1d50cd0c93f9', (select id from clinlims.localization where english = 'Cyclospora' and description = 'test name'), (select id from clinlims.localization where english = 'Cyclospora' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Onchocerca volvulus(Skin)' , '',  'Onchocerca' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Onchocerca volvulus' ,1880 , 'Onchocerca volvulus',  true, '853ab112-b115-4246-90cc-a494b1c93b1b', (select id from clinlims.localization where english = 'Onchocerca volvulus' and description = 'test name'), (select id from clinlims.localization where english = 'Onchocerca volvulus' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Leishmania(Skin)' , '',  'Leishmania' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'PARASITOLOGY' ) ,'Leishmania' ,1890 , 'Leishmania',  true, 'b8cebdeb-6b64-414a-849d-50360c75b062', (select id from clinlims.localization where english = 'Leishmania' and description = 'test name'), (select id from clinlims.localization where english = 'Leishmania' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Naisseria(Swab)' , '',  'Naisseria' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Naisseria' ,1900 , 'Naisseria',  true, '3deb7257-2789-437f-baf2-f026f65a1a35', (select id from clinlims.localization where english = 'Naisseria' and description = 'test name'), (select id from clinlims.localization where english = 'Naisseria' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Klebsiella(Swab)' , '',  'Klebsiella' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Klebsiella' ,1910 , 'Klebsiella',  true, '63bfb663-d517-4050-bcd3-b29701586cf7', (select id from clinlims.localization where english = 'Klebsiella' and description = 'test name'), (select id from clinlims.localization where english = 'Klebsiella' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Staphyloccoci(Swab)' , '',  'Staphyloccoci' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Staphyloccoci' ,1920 , 'Staphyloccoci',  true, '4bb8c190-ac41-40ce-960a-b38d03d0c3bd', (select id from clinlims.localization where english = 'Staphyloccoci' and description = 'test name'), (select id from clinlims.localization where english = 'Staphyloccoci' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Streprococci(Swab)' , '',  'Streprococci' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Streprococci' ,1930 , 'Streprococci',  true, '20f37b01-a198-45ba-897c-624432e6a0a7', (select id from clinlims.localization where english = 'Streprococci' and description = 'test name'), (select id from clinlims.localization where english = 'Streprococci' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Proteus(Swab)' , '',  'Proteus' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Proteus' ,1940 , 'Proteus',  true, 'b21359f6-731d-4776-ae49-ef73d660ee57', (select id from clinlims.localization where english = 'Proteus' and description = 'test name'), (select id from clinlims.localization where english = 'Proteus' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Shigella(Swab)' , '',  'Shigella' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Shigella' ,1950 , 'Shigella',  true, 'bfc65616-c646-4466-97bb-1744059ef182', (select id from clinlims.localization where english = 'Shigella' and description = 'test name'), (select id from clinlims.localization where english = 'Shigella' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Salmonella(Swab)' , '',  'Salmonella' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Salmonella' ,1960 , 'Salmonella',  true, '82de0b4c-e5e5-4efd-9a18-7407944fb580', (select id from clinlims.localization where english = 'Salmonella' and description = 'test name'), (select id from clinlims.localization where english = 'Salmonella' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'V. cholera(Swab)' , '',  'V.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'V. cholera' ,1970 , 'V. cholera',  true, '419f55d9-8037-4470-a7c2-fbff24988206', (select id from clinlims.localization where english = 'V. cholera' and description = 'test name'), (select id from clinlims.localization where english = 'V. cholera' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'E. coli(Swab)' , '',  'E.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'E. coli' ,1980 , 'E. coli',  true, '842fc532-ecaa-40e7-ac04-6e6baead0acf', (select id from clinlims.localization where english = 'E. coli' and description = 'test name'), (select id from clinlims.localization where english = 'E. coli' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'C. neoformans(Swab)' , '',  'C.' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'C. neoformans' ,1990 , 'C. neoformans',  true, '4de44f90-ed9b-4877-a6af-320d13c1ecff', (select id from clinlims.localization where english = 'C. neoformans' and description = 'test name'), (select id from clinlims.localization where english = 'C. neoformans' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Cardinella vaginalis(Swab)' , '',  'Cardinella' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Cardinella vaginalis' ,2000 , 'Cardinella vaginalis',  true, '9c7e5b8c-c57b-4c92-92f2-be2e119a4b79', (select id from clinlims.localization where english = 'Cardinella vaginalis' and description = 'test name'), (select id from clinlims.localization where english = 'Cardinella vaginalis' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Haemophilus(Swab)' , '',  'Haemophilus' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Haemophilus' ,2010 , 'Haemophilus',  true, '9a9fd876-568d-47ae-8a3e-9fd544d1666c', (select id from clinlims.localization where english = 'Haemophilus' and description = 'test name'), (select id from clinlims.localization where english = 'Haemophilus' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Bordotella pertusis(Swab)' , '',  'Bordotella' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Bordotella pertusis' ,2020 , 'Bordotella pertusis',  true, 'd949f743-0af5-4e7d-984e-33950b646ae1', (select id from clinlims.localization where english = 'Bordotella pertusis' and description = 'test name'), (select id from clinlims.localization where english = 'Bordotella pertusis' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Psuedomonas(Swab)' , '',  'Psuedomonas' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Psuedomonas' ,2030 , 'Psuedomonas',  true, '8bfa6afa-fbc5-41c0-98c1-0973ed1d935b', (select id from clinlims.localization where english = 'Psuedomonas' and description = 'test name'), (select id from clinlims.localization where english = 'Psuedomonas' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Coliforms(Swab)' , '',  'Coliforms' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Coliforms' ,2040 , 'Coliforms',  true, '8c072c39-1790-4511-8976-e6266a052255', (select id from clinlims.localization where english = 'Coliforms' and description = 'test name'), (select id from clinlims.localization where english = 'Coliforms' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Faecal coliforms(Swab)' , '',  'Faecal' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Faecal coliforms' ,2050 , 'Faecal coliforms',  true, 'f9deb784-8629-4584-98f2-0956d220b62f', (select id from clinlims.localization where english = 'Faecal coliforms' and description = 'test name'), (select id from clinlims.localization where english = 'Faecal coliforms' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Enterococcus faecalis(Swab)' , '',  'Enterococcus' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Enterococcus faecali' ,2060 , 'Enterococcus faecalis',  true, '73afc69e-fb57-4495-9351-f7028f4787aa', (select id from clinlims.localization where english = 'Enterococcus faecalis' and description = 'test name'), (select id from clinlims.localization where english = 'Enterococcus faecalis' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Total viable counts-22C(Swab)' , '',  'Total' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Total viable counts-' ,2070 , 'Total viable counts-22C',  true, '4524da74-0ffa-4fec-941c-e16178b41861', (select id from clinlims.localization where english = 'Total viable counts-22C' and description = 'test name'), (select id from clinlims.localization where english = 'Total viable counts-22C' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Total viable counts-37C(Swab)' , '',  'Total' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Total viable counts-' ,2080 , 'Total viable counts-37C',  true, '070e4e6b-5e1b-43ae-9d29-903300c80304', (select id from clinlims.localization where english = 'Total viable counts-37C' and description = 'test name'), (select id from clinlims.localization where english = 'Total viable counts-37C' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Clostridium(Swab)' , '',  'Clostridium' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'BACTERIOLOGY' ) ,'Clostridium' ,2090 , 'Clostridium',  true, 'bffa82c0-1bbe-4b36-934a-d2505189fd80', (select id from clinlims.localization where english = 'Clostridium' and description = 'test name'), (select id from clinlims.localization where english = 'Clostridium' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Full blood count(Blood)' , '',  'Full' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Full blood count' ,2100 , 'Full blood count',  true, 'a72a69aa-5a71-4890-b98c-76c980460159', (select id from clinlims.localization where english = 'Full blood count' and description = 'test name'), (select id from clinlims.localization where english = 'Full blood count' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='u/L') , 'Manual WBCcounts(Blood)' , '',  'Manual' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Manual WBCcounts' ,2110 , 'Manual WBCcounts',  true, '419d946c-84ca-4532-919c-b2829bae08ed', (select id from clinlims.localization where english = 'Manual WBCcounts' and description = 'test name'), (select id from clinlims.localization where english = 'Manual WBCcounts' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='mm/Hr') , 'Peripheral blood films(Swab)' , '',  'Peripheral' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Peripheral blood fil' ,2120 , 'Peripheral blood films',  true, '33566db4-f5e0-45bc-9ab8-684135a86d29', (select id from clinlims.localization where english = 'Peripheral blood films' and description = 'test name'), (select id from clinlims.localization where english = 'Peripheral blood films' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Erythrocyte Sedimentation rate(Blood)' , '',  'Erythrocyte' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Erythrocyte Sediment' ,2130 , 'Erythrocyte Sedimentation rate',  true, '58104761-b608-4fac-96a1-e2d35372770e', (select id from clinlims.localization where english = 'Erythrocyte Sedimentation rate' and description = 'test name'), (select id from clinlims.localization where english = 'Erythrocyte Sedimentation rate' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Sickling test(Blood)' , '',  'Sickling' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Sickling test' ,2140 , 'Sickling test',  true, '48cf399b-9e09-4f67-867e-0eb8cc041035', (select id from clinlims.localization where english = 'Sickling test' and description = 'test name'), (select id from clinlims.localization where english = 'Sickling test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Hb electrophoresis(Blood)' , '',  'Hb' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Hb electrophoresis' ,2150 , 'Hb electrophoresis',  true, '1319488f-385d-42bd-9d7e-3a9f8092ebce', (select id from clinlims.localization where english = 'Hb electrophoresis' and description = 'test name'), (select id from clinlims.localization where english = 'Hb electrophoresis' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='u/g') , 'G6PD screening(Blood)' , '',  'G6PD' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'G6PD screening' ,2160 , 'G6PD screening',  true, '9d994525-0e36-4490-b732-5bc46bf5aa5a', (select id from clinlims.localization where english = 'G6PD screening' and description = 'test name'), (select id from clinlims.localization where english = 'G6PD screening' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='Minutes') , 'Bleeding time(Blood)' , '',  'Bleeding' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Bleeding time' ,2170 , 'Bleeding time',  true, '57309890-69b9-4cea-b585-59ccc967a812', (select id from clinlims.localization where english = 'Bleeding time' and description = 'test name'), (select id from clinlims.localization where english = 'Bleeding time' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='Minutes') , 'Clotting time(Blood)' , '',  'Clotting' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Clotting time' ,2180 , 'Clotting time',  true, '981e7771-dc4f-4903-ad39-08a22f9bca50', (select id from clinlims.localization where english = 'Clotting time' and description = 'test name'), (select id from clinlims.localization where english = 'Clotting time' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='Seconds') , 'Prothrombin test(Blood)' , '',  'Prothrombin' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Prothrombin test' ,2190 , 'Prothrombin test',  true, '514b2912-3454-4a36-b0e1-e79c69e31f74', (select id from clinlims.localization where english = 'Prothrombin test' and description = 'test name'), (select id from clinlims.localization where english = 'Prothrombin test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='Seconds') , 'Partial prothrombin time(Blood)' , '',  'Partial' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Partial prothrombin ' ,2200 , 'Partial prothrombin time',  true, '5099de2f-2f81-45cd-a261-8318a1fd5ea0', (select id from clinlims.localization where english = 'Partial prothrombin time' and description = 'test name'), (select id from clinlims.localization where english = 'Partial prothrombin time' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Bone Marrow Aspirates(Blood)' , '',  'Bone' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Bone Marrow Aspirate' ,2210 , 'Bone Marrow Aspirates',  true, '89e51b22-43ef-43c5-bae1-88115d995c4c', (select id from clinlims.localization where english = 'Bone Marrow Aspirates' and description = 'test name'), (select id from clinlims.localization where english = 'Bone Marrow Aspirates' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Reticulocyte counts(Blood)' , '',  'Reticulocyte' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Reticulocyte counts' ,2220 , 'Reticulocyte counts',  true, '34ecaa43-25e1-46d2-8cf5-cc8a3a5fd536', (select id from clinlims.localization where english = 'Reticulocyte counts' and description = 'test name'), (select id from clinlims.localization where english = 'Reticulocyte counts' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/dl') , 'Haemoglobin(Blood)' , '',  'Haemoglobin' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Haemoglobin' ,2230 , 'Haemoglobin',  true, 'c160fe09-c6a3-4edf-bd7e-e47aeec6cdb8', (select id from clinlims.localization where english = 'Haemoglobin' and description = 'test name'), (select id from clinlims.localization where english = 'Haemoglobin' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='u/L') , 'CD4/CD8(Blood)' , '',  'CD4/CD8' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'CD4/CD8' ,2240 , 'CD4/CD8',  true, 'dbb73815-02f3-4d2e-b0ee-40e4cb62635c', (select id from clinlims.localization where english = 'CD4/CD8' and description = 'test name'), (select id from clinlims.localization where english = 'CD4/CD8' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'CD4%(Blood)' , '',  'CD4%' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'CD4%' ,2250 , 'CD4%',  true, '95c33662-a675-4238-af1e-91053e54043a', (select id from clinlims.localization where english = 'CD4%' and description = 'test name'), (select id from clinlims.localization where english = 'CD4%' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Peripheral Blood Films(Blood)' , '',  'Peripheral' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HEMATOLOGY' ) ,'Peripheral Blood Fil' ,2260 , 'Peripheral Blood Films',  true, '9591af60-aa5f-45e4-b644-de8342f91f8c', (select id from clinlims.localization where english = 'Peripheral Blood Films' and description = 'test name'), (select id from clinlims.localization where english = 'Peripheral Blood Films' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Tissue Impression(Smear)' , '',  'Tissue' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'CYTOLOGY' ) ,'Tissue Impression' ,2270 , 'Tissue Impression',  true, '56190b56-4280-46ed-a58b-b34d3acd36bb', (select id from clinlims.localization where english = 'Tissue Impression' and description = 'test name'), (select id from clinlims.localization where english = 'Tissue Impression' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Pap Smear(Smear)' , '',  'Pap' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'CYTOLOGY' ) ,'Pap Smear' ,2280 , 'Pap Smear',  true, '01a3c4c7-3299-4d5f-b69c-094ee0dc2ef1', (select id from clinlims.localization where english = 'Pap Smear' and description = 'test name'), (select id from clinlims.localization where english = 'Pap Smear' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Ascitic fluid(Smear)' , '',  'Ascitic' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'CYTOLOGY' ) ,'Ascitic fluid' ,2290 , 'Ascitic fluid',  true, '5759e0ad-c88f-4cca-bd8c-f1fcde340d1e', (select id from clinlims.localization where english = 'Ascitic fluid' and description = 'test name'), (select id from clinlims.localization where english = 'Ascitic fluid' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'CSF(Smear)' , '',  'CSF' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'CYTOLOGY' ) ,'CSF' ,2300 , 'CSF',  true, '102bf609-f48a-4df8-81bf-b54fc742cf20', (select id from clinlims.localization where english = 'CSF' and description = 'test name'), (select id from clinlims.localization where english = 'CSF' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Pleural fluid(Smear)' , '',  'Pleural' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'CYTOLOGY' ) ,'Pleural fluid' ,2310 , 'Pleural fluid',  true, '9d97a4f4-36e3-4856-93a6-78f90ff4bc1f', (select id from clinlims.localization where english = 'Pleural fluid' and description = 'test name'), (select id from clinlims.localization where english = 'Pleural fluid' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Cervix(Tissue)' , '',  'Cervix' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HISTOLOGY' ) ,'Cervix' ,2320 , 'Cervix',  true, 'cf038cd5-243a-4e6a-af55-2c19e8878723', (select id from clinlims.localization where english = 'Cervix' and description = 'test name'), (select id from clinlims.localization where english = 'Cervix' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Prostrate(Tissue)' , '',  'Prostrate' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HISTOLOGY' ) ,'Prostrate' ,2330 , 'Prostrate',  true, '404769ff-ea6b-49de-ad50-edb4b9f4aa69', (select id from clinlims.localization where english = 'Prostrate' and description = 'test name'), (select id from clinlims.localization where english = 'Prostrate' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Breast(Tissue)' , '',  'Breast' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HISTOLOGY' ) ,'Breast' ,2340 , 'Breast',  true, 'f6b6b98b-429d-49db-8c18-156f2b7bace5', (select id from clinlims.localization where english = 'Breast' and description = 'test name'), (select id from clinlims.localization where english = 'Breast' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Ovarian cyst(Tissue)' , '',  'Ovarian' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HISTOLOGY' ) ,'Ovarian cyst' ,2350 , 'Ovarian cyst',  true, '57ac0a75-f0e9-4272-a1af-2b6f3a373e3b', (select id from clinlims.localization where english = 'Ovarian cyst' and description = 'test name'), (select id from clinlims.localization where english = 'Ovarian cyst' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Fibroids(Tissue)' , '',  'Fibroids' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HISTOLOGY' ) ,'Fibroids' ,2360 , 'Fibroids',  true, '6ca2a7dd-ec06-47d3-9a71-dfb0e729dcf0', (select id from clinlims.localization where english = 'Fibroids' and description = 'test name'), (select id from clinlims.localization where english = 'Fibroids' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Lymph nodes(Tissue)' , '',  'Lymph' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'HISTOLOGY' ) ,'Lymph nodes' ,2370 , 'Lymph nodes',  true, '95042b1c-5587-4cd4-86ca-28346a6c6c89', (select id from clinlims.localization where english = 'Lymph nodes' and description = 'test name'), (select id from clinlims.localization where english = 'Lymph nodes' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Rapid Plasma Region(Blood)' , '',  'Rapid' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Rapid Plasma Region' ,2380 , 'Rapid Plasma Region',  true, '49ebd595-63c1-40a1-a6a7-ac531d2d7d48', (select id from clinlims.localization where english = 'Rapid Plasma Region' and description = 'test name'), (select id from clinlims.localization where english = 'Rapid Plasma Region' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'TPHA(Blood)' , '',  'TPHA' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'TPHA' ,2390 , 'TPHA',  true, 'fd7ed974-d251-4d7d-862f-d92cdbbac5e5', (select id from clinlims.localization where english = 'TPHA' and description = 'test name'), (select id from clinlims.localization where english = 'TPHA' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'ASO Test(Blood)' , '',  'ASO' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'ASO Test' ,2400 , 'ASO Test',  true, '01ac5b93-bbef-41dc-98a3-7e5ca3c0525e', (select id from clinlims.localization where english = 'ASO Test' and description = 'test name'), (select id from clinlims.localization where english = 'ASO Test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'HIV Test(Blood)' , '',  'HIV' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'HIV Test' ,2410 , 'HIV Test',  true, 'aa2bec5b-0cb7-4b49-8b0b-dbed38d536ce', (select id from clinlims.localization where english = 'HIV Test' and description = 'test name'), (select id from clinlims.localization where english = 'HIV Test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Widal test(Blood)' , '',  'Widal' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Widal test' ,2420 , 'Widal test',  true, '4abf95e3-5b63-4412-9386-e9aa228c3231', (select id from clinlims.localization where english = 'Widal test' and description = 'test name'), (select id from clinlims.localization where english = 'Widal test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Brucella test(Blood)' , '',  'Brucella' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Brucella test' ,2430 , 'Brucella test',  true, '8a35d4f6-e8ab-493a-85ae-d7ece8700fde', (select id from clinlims.localization where english = 'Brucella test' and description = 'test name'), (select id from clinlims.localization where english = 'Brucella test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Rheumatoid Factor Tests(Blood)' , '',  'Rheumatoid' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Rheumatoid Factor Te' ,2440 , 'Rheumatoid Factor Tests',  true, 'dac6fa57-d686-4051-8348-147e75b6ceb8', (select id from clinlims.localization where english = 'Rheumatoid Factor Tests' and description = 'test name'), (select id from clinlims.localization where english = 'Rheumatoid Factor Tests' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Cryptococcal Antigen(Blood)' , '',  'Cryptococcal' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Cryptococcal Antigen' ,2450 , 'Cryptococcal Antigen',  true, '9c59bebf-4002-4744-a1ce-b0a5501548e9', (select id from clinlims.localization where english = 'Cryptococcal Antigen' and description = 'test name'), (select id from clinlims.localization where english = 'Cryptococcal Antigen' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Helicobacter pylori test(Blood)' , '',  'Helicobacter' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Helicobacter pylori ' ,2460 , 'Helicobacter pylori test',  true, '3e8ca37b-34b7-4850-9cab-8323b8b7aeb4', (select id from clinlims.localization where english = 'Helicobacter pylori test' and description = 'test name'), (select id from clinlims.localization where english = 'Helicobacter pylori test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Hepatitis A Test(Blood)' , '',  'Hepatitis' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Hepatitis A Test' ,2470 , 'Hepatitis A Test',  true, '7464224a-ecbe-44e5-a73b-b2c15c5d2854', (select id from clinlims.localization where english = 'Hepatitis A Test' and description = 'test name'), (select id from clinlims.localization where english = 'Hepatitis A Test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Hepatitis B Test(Blood)' , '',  'Hepatitis' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Hepatitis B Test' ,2480 , 'Hepatitis B Test',  true, '46655d71-c5fe-4caa-b419-095a96867fb6', (select id from clinlims.localization where english = 'Hepatitis B Test' and description = 'test name'), (select id from clinlims.localization where english = 'Hepatitis B Test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Hepatitis C Test(Blood)' , '',  'Hepatitis' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Hepatitis C Test' ,2490 , 'Hepatitis C Test',  true, '909f2a4a-2c94-41b3-a140-784492151af1', (select id from clinlims.localization where english = 'Hepatitis C Test' and description = 'test name'), (select id from clinlims.localization where english = 'Hepatitis C Test' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , ( select id from clinlims.unit_of_measure where name='Copies/mL') , 'Viral Load(Blood)' , '',  'Viral' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Viral Load' ,2500 , 'Viral Load',  true, 'e9fecbce-7a18-473f-a21a-17a0a2206faa', (select id from clinlims.localization where english = 'Viral Load' and description = 'test name'), (select id from clinlims.localization where english = 'Viral Load' and description = 'test report name') );
INSERT INTO clinlims.test( id,  uom_id, description, loinc, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_code, sort_order, name, orderable, guid, name_localization_id, reporting_name_localization_id)
	VALUES ( nextval( 'clinlims.test_seq' ) , null , 'Formal Gel Test(Blood)' , '',  'Formal' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'SEROLOGY' ) ,'Formal Gel Test' ,2510 , 'Formal Gel Test',  true, '4cd9adef-4ac0-4752-914b-b6625373c7fb', (select id from clinlims.localization where english = 'Formal Gel Test' and description = 'test name'), (select id from clinlims.localization where english = 'Formal Gel Test' and description = 'test report name') );
